const words = [
  // Life stuff
  "Umbrella",
  "Newspaper",
  "Periodical",
  "Timetable",
  "Dental floss",
  "Razor",
  "Hair slide",
  
  // Words and phrases
  "Night cap",
  "One for the road",
  "Lightbulb moment",
  "Eureka",
  "Belt and braces",
  "Once upon a time",
  
  // Transport
  "Double decker bus",
  "Microlight",
  "Boy racer",
  "Penny farthing",
  "Spitfire",
  "Jumbo jet",
  "Joystick",
  "Rear-view mirror",
  "Exhaust pipe",
  "Intercity train",
  "Nightbus",
  "Campervan",
  "Skateboard",

  // Clothing and fashion
  "Handlebar moustache",
  "Wellington boots",
  "Duffle coat",
  "Pin-stripe suit",
  "Little black dress",
  "Drainpipe jeans",
  "Double-breasted jacket",
  "Stilleto",
  "Bermuda shorts",
  "Hawaiian shirt",
  "Bobble hat",
  "Christmas jumper",
  "Cravate",
  "Shoehorn",

  // Stationery
  "Fountain pen",
  "Crayon",
  "A3 Paper",
  "HB Pencil",
  "Postit",
  "Laminator",
  "Eraser",

  // Food and drink
  "Griddle",
  "Mac and cheese",
  "Cumberland sausage",
  "Jam roly-poly",
  "Spotted dick",
  "Nickerbocker glory",
  "Yorkshire pudding",
  "Watermelon",
  "Extra virgin olive oil",
  "Marshmallow",

  // Animals
  "Spaniel",
  "Omnivore",
  "Boa constrictor",
  "Orangutan",
  "Spider monkey",
  "Black widow",
  "Bald eagle",
  "Honey bee",

  // Plants and gardening
  "Monkey puzzle tree",
  "Venus fly trap",
  "Daisy",
  "Oak tree",
  "Horse chestnut",
  "Weeping willow",
  "Poison ivy",
  "Japanese knotweed",
  "Composter",
  "Rake",
  "Trellis",
  "Potting shed",
  "Greenhouse",

  // Art
  "Impressionism",
  "Jackson Pollock",
  "Pointillism",
  "Art Nouveau",
  "Calligraphy",
  "Canvas",
  "Abstract",
  "Avant garde",
  "Landscape",
  "Modern art",
  "Portfolio",
  "Relief",
  "Sketch",
  "Stencil",
  "Surrealism",

  // Education
  "Doctorate",
  "Undergraduate",
  "Classroom",
  "Playground",
  "Dinner lady",
  "Sports day",
  "Home time",
  "Curriculum",
  "Work experience",
  "Homework",
  "Spelling test",
  "Times tables",
  "Pencil case",
  "Lunch box",
  "Plimsoles",
  "Leotard",

  // Furniture
  "Crystal chandelier",
  "Tallboy",
  "Lazy susan",
  "Coffee table",
  "Floor lamp",
  "Chesterfield sofa",
  "Dressing table",
  "Vanity unit",
  "Blinds",
  "Curtain hook",
  "Patina",

  // Buildings and structures
  "Lighthouse",
  "Steeple",
  "Geodesic dome",
  "Firestation",
  "Chimney",
  "Warehouse",

  // Geography
  "Tundra",
  "Landlocked",
  "Foothills",
  "Marshland",
  "Tropical island",
  "Tributary",
  "Delta",
  "Ox-bow lake",
  "Glacier",
  "Sinkhole",
  "Peninsula",
  "Plateau",
  "Oasis",

  // Fairy tales
  "Fairy godmother",
  "Warlock",
  "Golden egg",
  "Magic wand",
  "Enchanted",
  "Troll",
  "Step mother",
  "Handsome prince",

  // Tech
  "Router",
  "Laptop",
  "Web browser",
  "Inkjet",
  "Webcam",
  "Dongle",
  "Flash drive",
  "Monitor",

  // Festive
  "Bauble",
  "Tinsel",
  "Holly",
  "Mistletoe",
  "Marzipan",
  "Brussel sprout",
  "Advent",
  "Carol",
  "Gingerbread",
  "Goodwill",
  "Eggnog",
  "Wreath",
  "Reindeer",
  "Sleigh",
  "Stable",

  // Holidays
  "Beach towel",
  "City break",
  "All inclusive",
  "Tourist",
  "Tour guide",
  "Resort",
  "Half-board",
  "Room-service",
]

export const getWord = () => words[Math.floor(Math.random() * words.length)]